name: Build typst
on:
  pull_request:
    branches:
      - main

jobs:
  build_release_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install required fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-fonts-extra

      - uses: typst-community/setup-typst@v3

      - name: Compile documents
        run: |
          typst compile thesis.typ thesis.pdf
          typst compile proposal.typ proposal.pdf
          typst compile registration_certificate.typ registration_certificate.pdf
